libraries:
  Movies:
    metadata_path:
    - file: metadata/Movies/star-trek-universe.yml
    - file: metadata/Movies/middle-earth-universe.yml
    - file: metadata/Movies/star-wars-universe.yml
    - file: metadata/Movies/wizarding-world-universe.yml
    - file: metadata/Movies/marvel.yml
    - file: metadata/Movies/alien-universe.yml
    - file: metadata/Movies/holiday.yml
    - file: metadata/Movies/movies-collections.yml

    overlay_path:
    - remove_overlays: false
    - reapply_overlay: false
    - pmm: resolution
      template_variables:
       back_color: "#000000D9"
    - pmm: mediastinger
      template_variables:
       horizontal_offset: 250       
    - pmm: video_format
    - pmm: language_count

    operations:
      library_name: Movies
      schedule: weekly(monday)
      mass_user_rating_update: mdb_tomatoes
      mass_critic_rating_update: imdb
      mass_audience_rating_update: tmdb
      metadata_backup:
        path: backup/Movies_backup.yml
        sync_tags: true
        add_blank_entries: true

  TV Shows:
        
    overlay_path:
    - remove_overlays: false
    - reapply_overlay: true
    - file: overlays/TV-Shows/show-type.yml
      template_variables:
        horizontal_align: center
        vertical_align: top
        vertical_offset: 0
        horizontal_offset: 0
        back_height: 85
        back_width: 1100
        font: config/custom_fonts/Avenir_95_Black.ttf
        font_size: 60
        back_color_miniseries: "#D1A32E"    
    - pmm: status
      template_variables:    
        horizontal_align: center
        vertical_align: top
        vertical_offset: 0
        horizontal_offset: 0
        back_height: 85
        back_width: 1100
        font: config/custom_fonts/Avenir_95_Black.ttf
        font_size: 60
        back_color_airing: "#016920"
        back_color_returning: "#81007F"
        back_color_canceled: "#ed1f1f"
        back_color_ended: "#000847"     
             
    - pmm: resolution
      template_variables:
       overlay_level: season
    - pmm: audio_codec
      template_variables:
        overlay_level: season
    - pmm: video_format
      template_variables:
        overlay_level: season
    operations:
      library_name: TV Shows
      schedule: weekly (tuesday)
      mass_user_rating_update: mdb_tomatoes
      mass_critic_rating_update: imdb
      mass_audience_rating_update: tmdb
      metadata_backup:
        path: backup/TV-Shows_backup.yml
        sync_tags: true
        add_blank_entries: true
      assets_for_all: true

playlist_files:
   - file: config/playlists.yml

settings:
  cache: true
  cache_expiration: 60
  asset_directory: /assets
  reports_directory: /reports
  asset_folders: true
  asset_depth: 2
  create_asset_folders: true
  prioritize_assets: false
  dimensional_asset_rename: false
  download_url_assets: true
  show_missing_season_assets: true
  show_missing_episode_assets: true
  show_asset_not_needed: true
  sync_mode: append
  minimum_items: 2
  default_collection_order:
  delete_below_minimum: true
  delete_not_scheduled: true
  run_again_delay: 2
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: true
  show_unconfigured: true
  show_filtered: false
  show_options: false
  show_missing: true
  show_missing_assets: true
  save_report: true
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  playlist_sync_to_user: all
  playlist_exclude_users:
  playlist_report: true
  verify_ssl: true
  custom_repo:
  check_nightly: false

plex:
  url:
  token:
  timeout: 60
  clean_bundles: false
  empty_trash: false
  optimize: false
  db_cache:
tmdb:
  apikey:
  language: en
  cache_expiration: 60
  region:
tautulli:                        # Can be individually specified per library as well
  url: 
  apikey: 
  cache_expiration: 60
  region:
trakt:
  client_id: 
  client_secret: 
  pin:
  authorization:
    access_token: 
    token_type: Bearer
    expires_in: 
    refresh_token: 
    scope: public
    created_at: 1702128444
mdblist:
  apikey: 
  cache_expiration: 60
